services:
  app:
    image: ghcr.io/vikram11/wellnesslogin:latest
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://neondb_owner:npg_bGmIk2FDtL1B@ep-hidden-boat-ajjf9pbs.c-3.us-east-2.aws.neon.tech/neondb?sslmode=require
      OLLAMA_API_KEY: bef1758095114d51be25ebb2d88679f8.BG34PpG7Eze4l82zNuWPA9Vy
      OLLAMA_MODEL: gemma4:31b-cloud
      NEXT_PUBLIC_VAPID_PUBLIC_KEY: BIkgoN9zFHVs5sj0a9vMglYZrCj79gleNUSMPNDfKHqg6N0wsLG_dcveyCyZ-gbua1LVQHTihcojBTagReyRbXU
      VAPID_PRIVATE_KEY: Mc15bCKK8Wu08TDSL6k1-nvOoA_5hL-ZJYPuCbhuX9E
      SMTP_HOST: smtp.hostinger.com
      SMTP_PORT: "465"
      SMTP_USER: update@wellnesslog.in
      SMTP_PASS: "Healthy-2026!"
      EMAIL_FROM: "WellnessLog.in <update@wellnesslog.in>"
      NEXTAUTH_URL: https://wellnesslog.in
    networks:
      - caddy_network
    labels:
      caddy: wellnesslog.in
      caddy.reverse_proxy: "{{upstreams 3000}}"

networks:
  caddy_network:
    external: true
